from web3 import Web3
import json
import os

# Connect to Ganache CLI (port 8545, matching truffle-config.js)
w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))

# Load contract address from environment variable (fallback to default)
contract_address = os.getenv(
    "CONTRACT_ADDRESS",
    "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
)

# Correct path to compiled ABI (generated by truffle compile)
abi_path = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "blockchain", "build", "contracts", "ESOPManagement.json"
)

with open(abi_path) as f:
    abi = json.load(f)["abi"]

contract = w3.eth.contract(
    address=Web3.to_checksum_address(contract_address),
    abi=abi
)

def get_connection_status():
    return w3.is_connected()